version: "3.7"
services:
  # hubot, the popular chatbot (add the bot user first and change the password before starting this image)
  hubot:
    image: rocketchat/hubot-rocketchat:latest
    container_name: ${PROJECTSHORT_NAME}hubot
    restart: unless-stopped
    environment:
      - ROCKETCHAT_URL=${ROCKETCHAT_URL}
      - ROCKETCHAT_ROOM=${ROCKETCHAT_ROOM}
      - ROCKETCHAT_USER=${ROCKETCHAT_USER}
      - ROCKETCHAT_PASSWORD=${ROCKETCHAT_PASSWORD}
      - BOT_NAME=${BOT_NAME}
  # you can add more scripts as you'd like here, they need to be installable by npm
      - EXTERNAL_SCRIPTS=${EXTERNAL_SCRIPTS}
    # depends_on:
    #   - rocketchat
    labels:
      - "traefik.enable=false"
    volumes:
      - ${SCRIPTS_PATH_HOST}:/home/hubot/scripts
  # this is used to expose the hubot port for notifications on the host on port 3001, e.g. for hubot-jenkins-notifier
    ports:
      - 3001:8080
